### ISSUE TITLE
Add support for servers using SRV records.

### ISSUE THREAD

**Issue by phinner** [Shawak/mindservlist#3]
Server owners can't add their server addresses if they are using SRV records. Is it possible to add support for it ?

**Comment by Shawak** [comment]
You may have an example server so I can test it?

**Comment by phinner** [comment]
`survival.md.xpdustry.fr` should redirect to `n1.xpdustry.fr:7002`

**Comment by Shawak** [comment]
Doesn't work for me:

![image](https://user-images.githubusercontent.com/3829602/203597781-f505905b-0b67-4459-bb8e-b5355c9ea5a1.png)

**Comment by phinner** [comment]
```sh
➜  ~ nslookup -type=SRV _mindustry._tcp.survival.md.xpdustry.fr. 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
_mindustry._tcp.survival.md.xpdustry.fr	service = 0 0 7002 n1.xpdustry.fr.

Authoritative answers can be found from:
```
You forgot the service (`_mindustry`) and the protocol (`_tcp`). I should have told you that.

**Comment by Shawak** [comment]
Do you know if there is a server on the serverlist (any of the jsons) which currently uses SRV?

**Comment by phinner** [comment]
Mindustry Español
 https://github.com/Anuken/Mindustry/blob/master/servers_v7.json#L8

**Comment by phinner** [comment]
You managed to find something or you want me to try PR-ing it ?

**Comment by Shawak** [comment]
I didn't take a look into it yet

**Comment by Shawak** [comment]
Added support for SRV entries in https://github.com/Shawak/mindservlist/commit/5f428457c07bcfe867fd50da99147c9e74d48dc9

**Comment by phinner** [comment]
Many thanks kind rust developer.
